export const LOGIN_REQUEST = "@auth/LOGIN_REQUEST";
export const LOGIN_SUCCESS="@auth/LOGIN_SUCCESS";
export const LOGIN_FAILURE = "@auth/LOGIN_FAILURE";
//TODO: DO NOT EXPORT DEFAULT

export const FORGOT_PASSWORD_SUCCESS="@auth/FORGOT_PASSWORD_SUCCESS";
